version: "3.9"

services:
  fastapi:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: 'fastapi'
    restart: always
    tty: true
    #expose:
     # - "8040"
    ports:
      - "8040:8040"
    working_dir: '/root/'
    volumes:
      - /Users/tanakatouma/vscode/fastapi-docker/src/:/root/src/
#      - /Users/tanakatouma/Documents/Docker_volumes/ds_mlops/fastapi:/root/fastapi/
